export const GET_PROJECT_DATA_REQUEST = "Get_PROJECT_DATA_REQUEST";
export const GET_PROJECT_DATA_SUCCESS = "GET_PROJECT_DATA_SUCCESS";
export const GET_PROJECT_DATA_FAILURE = "GET_PROJECT_DATA_FAILURE";

