export const GET_PROJECT_DATA_REQUEST = "GET_PROJECT_DATA_REQUEST";
export const GET_PROJECT_DATA_SUCCESS = "GET_PROJECT_DATA_SUCCESS";
export const GET_PROJECT_DATA_FAILURE = "GET_PROJECT_DATA_FAILURE";


export const POST_PROJECT_DATA_REQUEST = "POST_PROJECT_DATA_REQUEST";
export const POST_PROJECT_DATA_SUCCESS = "POST_PROJECT_DATA_SUCCESS";
export const POST_PROJECT_DATA_FAILURE = "POST_PROJECT_DATA_FAILURE";

export const GET_TOTAL_COUNT = "GET_TOTAL_COUNT";

export const PATCH_PROJECT_DATA_REQUEST = "PATCH_PROJECT_DATA_REQUEST";
export const PATCH_PROJECT_DATA_SUCCESS = "PATCH_PROJECT_DATA_SUCCESS";
export const PATCH_PROJECT_DATA_FAILURE = "PATCH_PROJECT_DATA_FAILURE";


export const GET_PROJECT_STATS_REQUEST = "GET_PROJECT_STATS_REQUEST";
export const GET_PROJECT_STATS_SUCCESS = "GET_PROJECT_STATS_SUCCESS";
export const GET_PROJECT_STATS_FAILURE = "GET_PROJECT_STATS_FAILURE";


export const GET_DEPARTMENT_STATS_REQUEST = "GET_DEPARTMENT_STATS_REQUEST";
export const GET_DEPARTMENT_STATS_SUCCESS = "GET_DEPARTMENT_STATS_SUCCESS";
export const GET_DEPARTMENT_STATS_FAILURE = "GET_DEPARTMENT_STATS_FAILURE";


